### PR TITLE
New Changes to Icelandic.

### PR DESCRIPTION
**Pull request by Nammi-namm**
New stuff, lots of new stuff, pluralisers added, all spaces replaced with tabs, all that good stuff. Added things to settings panels, and the new things implemented since last push. Still got a lot of the overly technical stuff left to do

### CODE REVIEW

**Review by Frooxius — CHANGES_REQUESTED** [review]
Thanks for the additions, but unfortunately I'll have to request changes. Changing the spaces to tabs has caused this file to conflict in its entirety, so I don't have a reasonable way to actually merge your changes. Can you please revert the formatting to the way it was before?

**Comment by Nammi-namm** [comment]
I've changed it back to four spaces instead of tabs, hopefully it's okay now.

**Comment by Frooxius** [comment]
Hmm it still seems to result in a whole-file conflict. If you check the "Files changed" tab, it shows what the current diff is. I'm not sure if you see the button for resolving conflicts on your end too, but clicking that will also show which parts conflict, it should normally only be a few lines that were changed.

**Comment by Frooxius** [comment]
The conflicts were resolved by @kazu0617 in this PR: https://github.com/Frooxius/NeosLocale/pull/250 The new changes should be merged now! Thank you for the additions, I'm going to close this one!

**Pull request closed without merging**
