### PR TITLE
New Strings for ja in Build 2020.12.18.33

### PR DESCRIPTION
**Pull request by kazu0617**
As the title says.

### CODE REVIEW

**Comment by kazu0617** [comment]
Now Conflicts Melnus' PR, so after merge it, fix conflict and Open it.

**Comment by Frooxius** [comment]
Is this ready for review or are you still working on this? I have merged Melnus' additions in the meanwhile.

**Comment by kazu0617** [comment]
I resolved conflict on GitHub, so ready for review. (I was using my smartphone by mistake, sorry for the confusion.)

**Comment by Frooxius** [comment]
Merged, thanks for the changes!

**Pull request merged**
