### PR TITLE
fix conflict #90

### PR DESCRIPTION
**Pull request by kazu0617**
I'm not sure if this is the best way to do it, but I was concerned that the Icelandic translation had been stopped for a long time, so I created a pull request that resolved the conflict.

In fact, it would have been smarter to recreate the commit to resolve the conflict, but I wanted to include the author's name in the commit, so I decided to just resolve the conflict.

この行いが最善なのかはわかりませんが、長らくアイスランドの翻訳が止まってしまっていることを懸念したのでコンフリクトを解消したプルリクエストを作成しました。

実際はコミットを作り直すことでもっとスマートにコンフリクトを解消することができますが、作者の名前をコミット内に併記したかったのであえてコンフリクトを解消するのみとしました。

### CODE REVIEW

**Comment by Frooxius** [comment]
Ah thank you for looking at the Icelandic translation as well! It seems that the file still conflicts with the main branch. Could the CleanJSON.py script potentially help here? It has helped fix the conflict for another locale.

**Comment by kazu0617** [comment]
That's OK. so... It use in 50a67e7 , please check it.

**Comment by kazu0617** [comment]
It seems whole conflict, so I re-create all of commits. plz check it.

**Comment by Frooxius** [comment]
Ah perfect, it's good  now, thank you so much! Merging!

**Pull request merged**
