### PR TITLE
Translate untranslated Esperanto strings

### PR DESCRIPTION
**Pull request by yellowcrash10**
Added translations for untranslated strings and words

### CODE REVIEW

**Comment by Frooxius** [comment]
Looks like there are some conflicts with translations provided by @Melnus. Which one of these is better?

```
<<<<<<< patch-1
        "World.Config.AutosaveInterval": "Intervalo de aŭtokonservado (minutoj):",
=======
        "World.Config.AutosaveInterval": "Aŭtokonserva intervalo (minutoj):",
>>>>>>> master
```

```
<<<<<<< patch-1
        "Settings.Haptics": "Tuŝ-retrokuplado",
=======
        "Settings.Haptics" : "Reagoj pri Haptics",
>>>>>>> master
```

**Comment by yellowcrash10** [comment]
I vote for my translation for the first one because it is in the same format as [the cleanup interval string](https://github.com/Frooxius/NeosLocale/blob/master/eo.json#L139), although both translations have essentially identical meaning. I'm also partial to my translation for the second one, which uses [the entry in Komputeko](https://komputeko.net/#haptic) and literally means "touch feedback". I'm unsure whether or not Melnus' translation means the same thing. @Melnus, what are your thoughts?

**Comment by Melnus** [comment]
First of all, thank you for translating the missing parts.
As for the first one, I agree with @yellowcrash10.

I'm just using what I thought would make sense without a literal translation.
so, I think there is a possibility that it will not be communicated to the user, 
but I thought that Haptics is a meaningful word by itself like "HTC VIVE" and "Oculus", so I did not translate it.

**Comment by yellowcrash10** [comment]
> but I thought that Haptics is a meaningful word by itself like "HTC VIVE" and "Oculus", so I did not translate it.

No worries; I thought that word was an invented word at first, which surprised me when I discovered the translation for it in Komputeko. Would you agree with the Komputeko translation, or do you think it is too literal?

**Comment by Melnus** [comment]
No, I think it's okay if there is a translated strings already.

**Comment by yellowcrash10** [comment]
Excellent! I believe this PR is ready to be merged.

**Comment by Frooxius** [comment]
Thank you for the changes!

**Pull request merged**
